---
title: "Tofu"
description: "And other people I hate"
author: "Tofu"
date: "8/27/2024"
draft: true
date-modified: "8/27/2024"
categories:
- introduction
---

When I was in 11th grade, there was a boy in my high school nicknamed Tofu. He left the school a few days after joining.

It was my physics teacher who told me about him. He was two years younger than me and only answered to Tofu. If she told me his government name at some point, I've forgotten it by now. She said he reminded her of me. He'd announced to her, and his classmates, that he refused to partake in  idle activies, he refused to "waste his time."

I was both touched and offended by the comparison. Touched because she meant it as a compliment, but offended to be compared to someone who sounded so anal.

I've known several people like Tofu in my life. People who refuse to let loose - or at least admit that they do. People who refuse to "waste their time." Who find meaning in driving themselves to the edge. Who only allow themselves the forbidden and self-indulgent sin of feeling pleasure when they are working themselves to the bone. A feeling only okay to feel under the blanket of intelligent technical work. At a point, starvation becomes gluttony. They reject hedonism only to find it in another form, unable to recognize it for what it is. God, why not just give yourself what you need?

I 