---
title: "Invisible and Always Visible"
description: "The role of absence in Columbus (2017)"
author: "Tofu"
date: "7/26/2024"
draft: true
date-modified: "7/26/2024"
categories:
- film
---

Jin finds a note and drawing in his recently-comatose father's notebook: a simple rectangle accompanied by the phrases "What is invisible and always visible" and "Much ado about nothing" with the word "nothing" underlined several times.

Jin attempts to find this rectangle in towers around Columbus, but is never quite convinced by them. Near the end of the movie, he tells Casey that he believes the drawing reflects this instead:

As in, the drawing is of the absence of rectangular space. And yet that absence is noticeable, sticking out like a sore thumb. In much the same way, Columbus is a film about what Casey and Jin are missing, what has always been absent in their lives and their inability to ignore it. The film is about lost opportunities, lost time, the incremental grief of each small loss piled up over time.

This building that Jin sees is the Columbus City Hall. Two brick walls extend, "reaching out toward one another yet not quite meeting." The gap is noticeable, dramatic even, emphatically demarcating the entrance to the hall. Like an architectural imagining of The Creation of Adam, Adam's and God's arms extended towards each other, but not touching. Some scholars think that it represents the unattainability of divine perfection by man. Another sort of absence, another sort of loss.

In the context of the film, the empty rectangular space represents a sort of anti-monument. A common feature of the anti-monument is inversion: voids instead of solids, absence instead of presence, darkness instead of light:

[photos of anti-monuments]

Anti-monuments, even moreso than traditional monuments, are linked to loss. The movement first appeared in the works of German artists dealing with the memory of the Holocaust. Anti-monuments challenge "the power of traditional monuments to suggest completeness, or a false sense of closure."

It is of note then that part of what Casey loves about architecture is its solidity, the strength of its mere presence. Throughout the film, the camera lingers on large structures that assert their presence. The camera stays still, as static as the buildings it watches. And through this, we come to understand Casey's world. The shots are centered, structured accutely. Lines are parallel to each other. This reflects Casey's way of viewing the world. When she is talking about her second favorite building to Jin, we see her warbled reflection in the building’s window. As Jin points out, Casey is just speaking about the building intellectually and not really conveying what moves her. When he prompts her to speak about it, we no longer see her reflection, but her herself. We see her mouth move, but can’t hear what she says. It is like there are no words really to describe why she is moved by it. At the end of Dante’s Paradiso, Dante reaches heaven where there is no physical geography. Just light and mist. The book ends as he sees God and fails to speak. He has truly reached the immaterial - beyond the physical, beyond language. Similarly here, we see Casey’s love for architecture swell to a point beyond words. She makes a rectangular shape with her hands. Similarly, when she shows Jin her third favorite building, she says, “There were nights that my mom just wouldn't come home at all. I had no clue where she was. That's when I started coming here. I found it weirdly comforting. In the middle of all the mess, in this fucking strip mall...there was this...This…” and then she makes a square with her hands, and we feel the solid shape she molds in the air.

Visually, the empty rectangular space is the antithesis of a church in the film. It towers into empty space, and though its presence is solid and concrete in much the same way as the other large structures in the film, it is slightly muted, in the background, covered up by trees.

[church photo]

When we meet Casey and Jin, neither are satisfied with their lives. They have dreams they’ve given up on and are content with simply sliding by. Casey loves architecture, but has for the most part given up on it to take care of her mother, a recovering meth addict. Jin has a strangled relationship with his ill father, who he has come to visit in Columbus. He tells his father's colleage that they haven't spoken in a year and though his father is a renowned architect, he himself doesn't "know shit about architecture... or care." This giving up on dreams requires an emotional detachment on both Casey and Jin’s part. Although the viewers get the chance to be alone with Casey and Jin, getting glimpses into their homes, sometimes we are not really with them. We are often standing just outside the door frame, close but not close enough.

[examples]

And yet, Casey and Jin push each other to change. Casey asks Jin at some point, "Do you think he's got a chance to recover? Even if it's just enough to go back to Seoul?" Jin replies, "God... I hope not." Casey is visibly upset by this. This is a conversation between someone devoted enough to their mother to turn down their dream career and someone with such a fraught relationship with their father that they don’t want their father to get better. She tells him that he doesn't want his dad to get better so that he does not have to mourn for him.

Jin, in turn, is frustrated by Casey's inability to follow her passions, always proking and prodding her to open up about her love of architecture despite her guardedness about it. Jin tells Casey she should pursue her career at New Haven saying, “The reason I'm telling you this… and the reason your mother is telling you this… is because you're smart and talented. You could do a lot better!”

Despite their arguments, Jin and Casey cannot help that they are now painfully aware of the absences in their life. Jin attends a tour of a house Casey signed him up for despite earlier proclaiming he didn't care about architecture and he visits his father in the hospital. He tells Eleanor that he visits his father “a lot” even.

At the end of the film, Casey decides to pursue her career, particularly after finding out her mom was not using again. And Jin spends more time with his father. He even buys his own apartment instead of moving back to Korea. Jin learns to stay, Casey learns to go.